language: c
os: linux
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
env:
 global:
   - PACKAGE=vhd-format
   - PINS="vhd-format:. vhd-format-lwt:."
   - DISTRO=alpine
   - TESTS=true
   - REVDEPS=true
 jobs:
   - OCAML_VERSION=4.06
   - OCAML_VERSION=4.08
   - OCAML_VERSION=4.10
   - OCAML_VERSION=4.11
